# Generated by Django 5.1.7 on 2025-04-12 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.IntegerField(default=999)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('positions', models.JSONField(default=list)),
                ('interest_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('skill_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('location_preference', models.JSONField(default=list)),
                ('owned', models.ManyToManyField(blank=True, related_name='owners', to='projects.project')),
                ('projects', models.ManyToManyField(blank=True, related_name='contributors', to='projects.project')),
            ],
        ),
    ]
