# Generated by Django 5.1.7 on 2025-04-13 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest_tags',
            new_name='colleges',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='skill_tags',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_preference',
            new_name='location_preferences',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='positions',
            new_name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_id',
            field=models.CharField(default=999),
        ),
    ]
