# Generated by Django 5.1.7 on 2025-03-26 04:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_owned_user_projects_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tags',
            new_name='interest_tags',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='location_preference',
        ),
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None),
        ),
    ]
