# Generated by Django 5.1.6 on 2025-03-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_images_project_slider_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='slider_images',
            new_name='images',
        ),
    ]
