# Generated by Django 5.1.6 on 2025-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('match_percentage', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('followers', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('positions', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
