# Generated by Django 5.1.7 on 2025-04-12 20:52

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('positions', models.JSONField(default=list)),
                ('image_url', models.ImageField(upload_to='projects/')),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('match_percentage', models.FloatField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('interest_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('skill_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('full_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('other_contact', models.CharField(blank=True, max_length=225, null=True)),
                ('updates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=540), blank=True, null=True, size=None)),
                ('wanted_description', models.CharField(blank=True, max_length=540, null=True)),
            ],
        ),
    ]
