# Generated by Django 5.1.6 on 2025-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
