# Generated by Django 5.1.7 on 2025-04-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='match_percentage',
        ),
    ]
