# Generated by Django 5.1.6 on 2025-03-25 04:36

from django.db import migrations
import uuid

def populate_uuids(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        project.project_id = uuid.uuid4()
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_email_project_full_description_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_uuids),
    ]
