# Generated by Django 5.1.7 on 2025-03-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_members_project_members'),
        ('userauth', '0003_rename_tags_user_interest_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_projects', to='userauth.user'),
        ),
    ]
