name: Backend Tests

on:
  push:
    branches:
      - ci/cd-setup
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations
        run: |
          source venv/bin/activate
          python backend/manage.py migrate

      - name: Run backend tests
        run: |
          source venv/bin/activate
          python backend/manage.py test
